name: gp
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py38h50d1736_1
  - argon2-cffi=20.1.0=py38h5406a74_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.2.3=pyh44b312d_0
  - brotlipy=0.7.0=py38h5406a74_1001
  - ca-certificates=2020.12.5=h033912b_0
  - certifi=2020.12.5=py38h50d1736_1
  - cffi=1.14.4=py38h979bc6b_1
  - chardet=4.0.0=py38h50d1736_1
  - cryptography=3.3.1=py38h6b4ec92_1
  - cycler=0.10.0=py_2
  - dbus=1.13.6=h0c50699_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.9=h046ec9c_3
  - freetype=2.10.4=h4cff582_1
  - gettext=0.19.8.1=h7937167_1005
  - glib=2.66.4=h22858aa_2
  - glib-tools=2.66.4=h22858aa_2
  - icu=67.1=hb1e8313_0
  - idna=2.10=pyh9f0ad1d_0
  - igl=2.2.1=py38hd38ea32_1
  - importlib-metadata=3.4.0=py38h50d1736_0
  - importlib_metadata=3.4.0=hd8ed1ab_0
  - ipydatawidgets=4.2.0=pyhd3deb0d_0
  - ipykernel=5.4.2=py38h9bb44b7_0
  - ipython=7.18.1=py38h1cdfbd6_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jedi=0.18.0=py38h50d1736_2
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=hbcb3906_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38h50d1736_5
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.0=py38h50d1736_1
  - jupyterlab=2.2.0=py_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - kiwisolver=1.3.1=py38hd9c93a9_1
  - krb5=1.17.2=h60d9502_0
  - lcms2=2.11=h11f7e16_1
  - libblas=3.9.0=7_openblas
  - libcblas=3.9.0=7_openblas
  - libclang=10.0.1=default_hf57f61e_1
  - libcxx=11.0.1=habf9029_0
  - libedit=3.1.20191231=h0678c8f_2
  - libffi=3.3=h046ec9c_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_17
  - libgfortran5=9.3.0=h6c81a4c_17
  - libglib=2.66.4=h7424822_2
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=7_openblas
  - libllvm10=10.0.1=h009f743_3
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libpng=1.6.37=h7cec526_2
  - libpq=12.3=h7049927_3
  - libsodium=1.0.18=hbcb3906_1
  - libtiff=4.2.0=h355d032_0
  - libuv=1.38.0=h0b31af3_0
  - libwebp-base=1.1.0=hbcb3906_3
  - llvm-openmp=11.0.1=h7c73e74_0
  - lz4-c=1.9.3=h046ec9c_0
  - markupsafe=1.1.1=py38h5406a74_3
  - matplotlib=3.3.3=py38h50d1736_0
  - matplotlib-base=3.3.3=py38hdcc317e_0
  - meshplot=0.4.0=pyh9f0ad1d_1
  - mistune=0.8.4=py38h5406a74_1003
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hfb8f7af_2
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38h50d1736_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=h2e338ed_4
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - nodejs=14.7.0=hdde0ff8_0
  - notebook=6.2.0=py38h50d1736_0
  - nspr=4.29=hbc8d48c_1
  - nss=3.47=hc0980d9_0
  - numpy=1.19.5=py38h6ced74f_1
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1i=h35c211d_0
  - packaging=20.8=pyhd3deb0d_0
  - pandoc=2.11.4=h35c211d_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py38hc1d52f7_1
  - pip=21.0=pyhd8ed1ab_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.14=pyha770c72_0
  - prompt_toolkit=3.0.14=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.4=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h50d1736_7
  - pyqt-impl=5.12.3=py38h721a93c_7
  - pyqt5-sip=4.19.18=py38h5745d40_7
  - pyqtchart=5.12=py38h721a93c_7
  - pyqtwebengine=5.12.1=py38h721a93c_7
  - pyrsistent=0.17.3=py38h5406a74_2
  - pysocks=1.7.1=py38h50d1736_3
  - python=3.8.6=h624753d_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pythreejs=2.2.1=pyh9f0ad1d_0
  - pyzmq=21.0.1=py38h1cb0b96_0
  - qt=5.12.9=h717870c_0
  - qtconsole=5.0.2=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h0678c8f_2
  - requests=2.25.1=pyhd3deb0d_0
  - scipy=1.6.0=py38h95ea19e_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h50d1736_3
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h17101e1_0
  - terminado=0.9.2=py38h50d1736_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=h0419947_1
  - tornado=6.1=py38h5406a74_1
  - traitlets=5.0.5=py_0
  - traittypes=0.2.1=pyh9f0ad1d_2
  - urllib3=1.26.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py38h50d1736_4
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.3=h74dc148_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.8=hf387650_1
prefix: /Users/siqi/anaconda3/envs/gp

